### ISSUE TITLE
Unhandled expr() node {FullComment} (ast line nr node.ast_line_nr ):

### ISSUE THREAD

**Issue by Shinyzenith** [vlang/c2v#47] opened 2022-07-15 22:27 UTC
Full error log: http://0x0.st/o1yY.txt
Source code: https://git.sr.ht/~shinyzenith/NextWM/tree/master/item/nextctl/nextctl.c

**Comment by ArtemkaKun** [comment] 2022-07-16 05:31
I think this is a duplicate of #4. 
What if you will remove all comments from your code and try again?

**Comment by Shinyzenith** [comment] 2022-07-16 09:20
> I think this is a duplicate of #4. 
> What if you will remove all comments from your code and try again?
Removing comments fixes the issue.

**Closed** 2022-07-16 09:32 UTC
Labels: bug, duplicate

**Comment by medvednikov** [comment] 2022-07-16 09:45
@ArtemkaKun #4 was fixed 4 hours ago, but this issue still remains. It should be open then.

**Comment by ArtemkaKun** [comment] 2022-07-16 09:47
Sorry, I messed up. It's duplicate of #3 :)
